version: '3.8'

services:
  mibu:
    build:
      context: .
      dockerfile: ./docker/mibu/Dockerfile
    container_name: myfo__mibu
    volumes:
      - ./node_modules:/mibu/node_modules
      - ./public:/mibu/public:ro
      - ./src:/mibu/src:ro
      - ./.env:/mibu/.env:ro
      - ./.eslintignore:/mibu/.eslintignore:ro
      - ./.eslintrc.js:/mibu/.eslintrc.js:ro
      - ./.yarnrc:/mibu/.yarnrc:ro
      - ./jsconfig.json:/mibu/jsconfig.json:ro
      - ./package.json:/mibu/package.json:ro
      - ./yarn.lock:/mibu/yarn.lock
    ports:
      - '0.0.0.0:3000:3000'
