name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - created

jobs:
  test:
    if: github.event_name != 'release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: make test

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/master')
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Create release
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: node dev/scripts/gh-release.js

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        uses: yarn build
      - name: Deploy
        env:
          BROWSER: 'none'
          GENERATE_SOURCEMAP: 'false'
          REACT_APP_APP_NAME: 'myfolab'
          REACT_APP_API_BASE_URL: 'https://api.myfolab.com'
          REACT_APP_PORTFOLIO_BASE_URL: 'https://portfolio.myfolab.com'
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        uses: yarn netlify deploy --dir=build --prod
